services:
  api:
    build: .
    container_name: news_api
    ports:
      - "8010:8010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./config.yaml:/app/config.yaml
